# Generated by Django 6.1 on 2026-09-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('timeline', models.CharField(blank=True, max_length=255)),
                ('responsibility', models.CharField(blank=True, max_length=255)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('budget_currency', models.CharField(default='KES', max_length=3)),
                ('remarks', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['objective', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('baseline_year', models.CharField(blank=True, max_length=9)),
                ('notes', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_indicators', to='icpd.activity')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icpd_activity_indicators', to='indicators.indicator')),
            ],
            options={
                'ordering': ['activity', 'indicator'],
            },
        ),
        migrations.CreateModel(
            name='IndicatorYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30')], max_length=7)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('achievement_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('achieved', 'Achieved'), ('not_reported', 'Not Reported')], default='not_reported', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('activity_indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_data', to='icpd.activityindicator')),
            ],
            options={
                'ordering': ['financial_year'],
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='icpd.commitment')),
            ],
            options={
                'ordering': ['commitment', 'sort_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='icpd.objective'),
        ),
        migrations.AddConstraint(
            model_name='activityindicator',
            constraint=models.UniqueConstraint(fields=('activity', 'indicator'), name='unique_icpd_indicator_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='indicatoryeardata',
            constraint=models.UniqueConstraint(fields=('activity_indicator', 'financial_year'), name='unique_icpd_indicator_financial_year'),
        ),
    ]
