# Generated by Django 6.1 on 2026-09-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityYearData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30')], max_length=7)),
                ('expenditure_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual expenditure in KES millions for this financial year.', max_digits=20, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_expenditure', to='icpd.activity')),
            ],
            options={
                'ordering': ['financial_year'],
                'constraints': [models.UniqueConstraint(fields=('activity', 'financial_year'), name='unique_icpd_activity_financial_year')],
            },
        ),
    ]
