# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0004_alter_activityindicator_code'),
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_restricted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='icpd_commitment_access_policies', to='users.role')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='icpd_commitment_access_policies', to='users.user')),
                ('commitment', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='access_policy', to='icpd.commitment')),
            ],
            options={
                'verbose_name': 'Commitment access policy',
                'verbose_name_plural': 'Commitment access policies',
            },
        ),
    ]