# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0002_commitmentaccesspolicy'),
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentNarrativeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_status', models.TextField()),
                ('takeaways_and_priority_next_steps', models.TextField()),
                ('abbreviations', models.TextField(blank=True)),
                ('executive_summary', models.TextField()),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='icpd_narrative_reports', to='users.user')),
                ('commitment', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='narrative_reports', to='icpd.commitment')),
            ],
            options={
                'verbose_name': 'Commitment narrative report',
                'verbose_name_plural': 'Commitment narrative reports',
                'ordering': ['commitment', 'author'],
            },
        ),
        migrations.AddConstraint(
            model_name='commitmentnarrativereport',
            constraint=models.UniqueConstraint(fields=('commitment', 'author'), name='unique_icpd_narrative_report_author'),
        ),
    ]