# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0003_commitmentnarrativereport'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commitmentnarrativereport',
            name='unique_icpd_narrative_report_author',
        ),
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='financial_year',
            field=models.CharField(choices=[('2019/20', '2019/20'), ('2020/21', '2020/21'), ('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30')], default='2025/26', max_length=7),
        ),
        migrations.AlterModelOptions(
            name='commitmentnarrativereport',
            options={'ordering': ['commitment', 'financial_year', 'author'], 'verbose_name': 'Commitment narrative report', 'verbose_name_plural': 'Commitment narrative reports'},
        ),
        migrations.AddConstraint(
            model_name='commitmentnarrativereport',
            constraint=models.UniqueConstraint(fields=('commitment', 'author', 'financial_year'), name='unique_icpd_narrative_report_author_year'),
        ),
    ]