# Generated by Django 6.1 on 2026-09-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0003_decouple_activity_indicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityindicator',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
