# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


FINANCIAL_YEAR_CHOICES = [
    ('2019/20', '2019/20'),
    ('2020/21', '2020/21'),
    ('2021/22', '2021/22'),
    ('2022/23', '2022/23'),
    ('2023/24', '2023/24'),
    ('2024/25', '2024/25'),
    ('2025/26', '2025/26'),
    ('2026/27', '2026/27'),
    ('2027/28', '2027/28'),
    ('2028/29', '2028/29'),
    ('2029/30', '2029/30'),
]


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0004_commitmentnarrativereport_financial_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityyeardata',
            name='financial_year',
            field=models.CharField(choices=FINANCIAL_YEAR_CHOICES, max_length=7),
        ),
        migrations.AlterField(
            model_name='indicatoryeardata',
            name='financial_year',
            field=models.CharField(choices=FINANCIAL_YEAR_CHOICES, max_length=7),
        ),
    ]