# Generated by Django 5.2 on 2026-09-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0005_expand_financial_year_choices'),
    ]

    operations = [
        migrations.AddField(model_name='commitmentnarrativereport', name='introduction', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commitmentnarrativereport', name='other_actor_contributions', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commitmentnarrativereport', name='facilitating_factors', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commitmentnarrativereport', name='challenges', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commitmentnarrativereport', name='opportunities', field=models.TextField(blank=True)),
        migrations.AddField(model_name='commitmentnarrativereport', name='conclusion_and_recommendations', field=models.TextField(blank=True)),
    ]