# Generated by Django 5.2 on 2026-09-14

from django.db import migrations, models


def disambiguate_duplicate_indicator_names(apps, schema_editor):
    ActivityIndicator = apps.get_model('icpd', 'ActivityIndicator')
    seen_names = set()
    for indicator in ActivityIndicator.objects.order_by('activity_id', 'name', 'id'):
        key = (indicator.activity_id, indicator.name)
        if key not in seen_names:
            seen_names.add(key)
            continue
        suffix = f' ({indicator.code or indicator.pk})'
        indicator.name = f'{indicator.name[:500 - len(suffix)]}{suffix}'
        indicator.save(update_fields=['name'])
        seen_names.add((indicator.activity_id, indicator.name))


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0006_commitment_narrative_sections'),
    ]

    operations = [
        migrations.RunPython(
            disambiguate_duplicate_indicator_names,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='commitment',
            constraint=models.UniqueConstraint(
                fields=('title',),
                name='unique_icpd_commitment_title',
            ),
        ),
        migrations.AddConstraint(
            model_name='objective',
            constraint=models.UniqueConstraint(
                fields=('commitment', 'title'),
                name='unique_icpd_objective_per_commitment',
            ),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(
                fields=('objective', 'title'),
                name='unique_icpd_activity_per_objective',
            ),
        ),
        migrations.AddConstraint(
            model_name='activityindicator',
            constraint=models.UniqueConstraint(
                fields=('activity', 'name'),
                name='unique_icpd_indicator_name_per_activity',
            ),
        ),
    ]