# Generated by Django 5.2 on 2026-09-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0007_prevent_duplicate_planning_entries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IcpdActualSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('achievement_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('achieved', 'Achieved'), ('not_reported', 'Not Reported')], default='not_reported', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('returned', 'Returned for correction'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_icpd_actual_submissions', to=settings.AUTH_USER_MODEL)),
                ('indicator_year_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_submissions', to='icpd.indicatoryeardata')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_icpd_actual_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icpd_actual_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['indicator_year_data', 'organization', 'submitted_by']},
        ),
        migrations.CreateModel(
            name='IcpdExpenditureSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('2019/20', '2019/20'), ('2020/21', '2020/21'), ('2021/22', '2021/22'), ('2022/23', '2022/23'), ('2023/24', '2023/24'), ('2024/25', '2024/25'), ('2025/26', '2025/26'), ('2026/27', '2026/27'), ('2027/28', '2027/28'), ('2028/29', '2028/29'), ('2029/30', '2029/30')], max_length=7)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('expenditure_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('returned', 'Returned for correction'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_submissions', to='icpd.activity')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_icpd_expenditure_submissions', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returned_icpd_expenditure_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='icpd_expenditure_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['activity', 'financial_year', 'organization', 'submitted_by']},
        ),
        migrations.CreateModel(
            name='IcpdSubmissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('actual', 'Actual'), ('expenditure', 'Expenditure')], max_length=20)),
                ('submission_id', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('submitted', 'Submitted'), ('returned', 'Returned'), ('approved', 'Approved')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icpd_submission_audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(model_name='icpdactualsubmission', constraint=models.UniqueConstraint(fields=('indicator_year_data', 'submitted_by'), name='unique_icpd_actual_submission_per_user_year')),
        migrations.AddConstraint(model_name='icpdexpendituresubmission', constraint=models.UniqueConstraint(fields=('activity', 'financial_year', 'submitted_by'), name='unique_icpd_expenditure_submission_per_user_year')),
        migrations.AddIndex(model_name='icpdsubmissionaudit', index=models.Index(fields=['submission_type', 'submission_id', '-created_at'], name='icpd_icpd_s_submiss_9adf5d_idx')),
    ]