# Generated by Django 5.2 on 2026-09-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0008_icpd_submission_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='icpdsubmissionaudit',
            new_name='icpd_icpdsu_submiss_f2ae5b_idx',
            old_name='icpd_icpd_s_submiss_9adf5d_idx',
        ),
    ]