# Generated by Django 5.2 on 2026-09-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_actual_submissions(apps, schema_editor):
    ActualSubmission = apps.get_model('icpd', 'IcpdActualSubmission')
    ExpenditureSubmission = apps.get_model('icpd', 'IcpdExpenditureSubmission')
    for actual in ActualSubmission.objects.select_related('indicator_year_data__activity_indicator__activity'):
        activity = actual.indicator_year_data.activity_indicator.activity
        report, _ = ExpenditureSubmission.objects.get_or_create(
            activity=activity,
            financial_year=actual.indicator_year_data.financial_year,
            defaults={
                'submitted_by': actual.submitted_by,
                'organization': actual.organization,
                'workflow_status': actual.workflow_status,
                'submitted_at': actual.submitted_at,
                'approved_by': actual.approved_by,
                'approved_at': actual.approved_at,
                'returned_by': actual.returned_by,
                'returned_at': actual.returned_at,
                'return_reason': actual.return_reason,
            },
        )
        actual.activity_report = report
        actual.save(update_fields=['activity_report'])


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0009_rename_submission_audit_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icpdactualsubmission',
            name='activity_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_submissions', to='icpd.icpdexpendituresubmission'),
        ),
        migrations.RunPython(link_existing_actual_submissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='icpdactualsubmission',
            name='activity_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_submissions', to='icpd.icpdexpendituresubmission'),
        ),
        migrations.RemoveConstraint(model_name='icpdactualsubmission', name='unique_icpd_actual_submission_per_user_year'),
        migrations.RemoveConstraint(model_name='icpdexpendituresubmission', name='unique_icpd_expenditure_submission_per_user_year'),
        migrations.AddConstraint(model_name='icpdactualsubmission', constraint=models.UniqueConstraint(fields=('indicator_year_data', 'activity_report'), name='unique_icpd_actual_submission_per_activity_report')),
        migrations.AddConstraint(model_name='icpdexpendituresubmission', constraint=models.UniqueConstraint(fields=('activity', 'financial_year'), name='unique_icpd_activity_report_per_financial_year')),
        migrations.AlterModelOptions(name='icpdactualsubmission', options={'ordering': ['indicator_year_data', 'organization', 'submitted_by']}),
        migrations.AlterModelOptions(name='icpdexpendituresubmission', options={'ordering': ['activity', 'financial_year']}),
    ]