# Generated by Django 5.2 on 2026-09-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def initialize_existing_narratives(apps, schema_editor):
    NarrativeReport = apps.get_model('icpd', 'CommitmentNarrativeReport')
    seen = set()
    for narrative in NarrativeReport.objects.order_by('commitment_id', 'financial_year', '-updated_at', '-pk'):
        key = (narrative.commitment_id, narrative.financial_year)
        if key in seen:
            narrative.delete()
            continue
        seen.add(key)
    for narrative in NarrativeReport.objects.filter(submitted_at__isnull=True):
        narrative.submitted_at = narrative.updated_at or narrative.created_at or timezone.now()
        narrative.save(update_fields=['submitted_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0011_activity_responsible_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_icpd_narrative_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='organization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commitmentnarrativereport',
            name='workflow_status',
            field=models.CharField(choices=[('submitted', 'Submitted for review'), ('approved', 'Approved')], default='submitted', max_length=20),
        ),
        migrations.RunPython(initialize_existing_narratives, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='commitmentnarrativereport',
            name='unique_icpd_narrative_report_author_year',
        ),
        migrations.AddConstraint(
            model_name='commitmentnarrativereport',
            constraint=models.UniqueConstraint(fields=('commitment', 'financial_year'), name='unique_icpd_narrative_report_per_financial_year'),
        ),
    ]