# Generated by Django 5.2 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('icpd', '0012_commitment_narrative_submission_workflow'),
	]

	operations = [
		migrations.RemoveField(
			model_name='commitmentnarrativereport',
			name='organization',
		),
		migrations.AddField(
			model_name='activity',
			name='cumulative_target_is_static',
			field=models.BooleanField(default=False, help_text='Use the latest annual target as the cumulative target instead of adding targets across years.'),
		),
	]