# Generated by Django 6.1 on 2026-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icpd', '0013_remove_narrative_organization_add_activity_cumulative_target_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentnarrativereport',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for review'), ('approved', 'Approved')], default='submitted', max_length=20),
        ),
    ]
