# Generated by Django 5.1.4 on 2026-06-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly name shown to users', max_length=100),
        ),
    ]
