# Generated by Django 5.1.4 on 2026-06-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verified_at_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='color',
            field=models.CharField(blank=True, help_text="CSS color class (e.g., 'primary', 'success')", max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap icon name (e.g., 'bi-person')", max_length=50),
        ),
    ]
