# Generated by Django 5.1.4 on 2026-06-30 10:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
        ('users', '0004_role_color_role_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_system_settings', 'Can manage system settings'), ('can_approve_data', 'Can approve data'), ('can_manage_indicators', 'Can manage indicators'), ('can_manage_thematic_areas', 'Can manage thematic areas'), ('can_import_data', 'Can import data'), ('can_manage_partners', 'Can manage partners'), ('can_manage_projects', 'Can manage projects'), ('can_view_county_data', 'Can view county data'), ('can_manage_county_data', 'Can manage county data')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, help_text='Higher priority roles can manage lower priority roles'),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_user_agent',
            field=models.TextField(blank=True, help_text='User agent of last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of failed OTP attempts'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('SUBMIT', 'Submit'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('RESET', 'Reset'), ('FAILED', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="System name for the role (e.g., 'admin', 'data_entry')", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user was approved', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.ForeignKey(blank=True, help_text='County this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.county'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's email has been verified"),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's account has been verified by an admin"),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Account lockout expiry timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization name', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when OTP was generated', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, help_text='Hashed OTP for secure verification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number with country code', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message='Enter a valid phone number (e.g., +254712345678)')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, help_text="User's role for permissions", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='users_audit_model_n_fb8a47_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name', 'is_active'], name='users_role_name_cd4d31_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['priority'], name='users_role_priorit_097429_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_user_role_id_08cc48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['county'], name='users_user_county__f45f2a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_verified', 'is_active'], name='users_user_is_veri_6fe005_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_user_deleted_37c818_idx'),
        ),
    ]
