# Generated by Django 5.1.4 on 2026-06-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_auditlog_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('view_dashboard', 'Can view dashboard'), ('view_data_entry', 'Can view data entry'), ('add_data_entry', 'Can add data entry'), ('change_data_entry', 'Can change data entry'), ('delete_data_entry', 'Can delete data entry'), ('view_indicators', 'Can view indicators'), ('add_indicators', 'Can add indicators'), ('change_indicators', 'Can change indicators'), ('delete_indicators', 'Can delete indicators'), ('view_reports', 'Can view reports'), ('add_reports', 'Can add reports'), ('change_reports', 'Can change reports'), ('delete_reports', 'Can delete reports'), ('export_reports', 'Can export reports'), ('view_partners', 'Can view partners'), ('add_partners', 'Can add partners'), ('change_partners', 'Can change partners'), ('delete_partners', 'Can delete partners'), ('view_projects', 'Can view projects'), ('add_projects', 'Can add projects'), ('change_projects', 'Can change projects'), ('delete_projects', 'Can delete projects'), ('view_users', 'Can view users'), ('add_users', 'Can add users'), ('change_users', 'Can change users'), ('delete_users', 'Can delete users'), ('view_settings', 'Can view settings'), ('add_settings', 'Can add settings'), ('change_settings', 'Can change settings'), ('delete_settings', 'Can delete settings'), ('view_audit_log', 'Can view audit log'), ('view_county_data', 'Can view county data'), ('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_system_settings', 'Can manage system settings'), ('can_approve_data', 'Can approve data'), ('can_manage_indicators', 'Can manage indicators'), ('can_manage_thematic_areas', 'Can manage thematic areas'), ('can_import_data', 'Can import data'), ('can_manage_partners', 'Can manage partners'), ('can_manage_projects', 'Can manage projects'), ('can_manage_county_data', 'Can manage county data')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
