# Generated by Django 5.1.4 on 2026-06-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'permissions': [('view_dashboard', 'Can view dashboard'), ('add_dashboard', 'Can add dashboard'), ('change_dashboard', 'Can change dashboard'), ('delete_dashboard', 'Can delete dashboard'), ('view_reports', 'Can view reports'), ('add_reports', 'Can add reports'), ('change_reports', 'Can change reports'), ('delete_reports', 'Can delete reports'), ('export_reports', 'Can export reports'), ('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_system_settings', 'Can manage system settings'), ('can_approve_data', 'Can approve data'), ('can_manage_indicators', 'Can manage indicators'), ('can_manage_thematic_areas', 'Can manage thematic areas'), ('can_import_data', 'Can import data'), ('can_manage_partners', 'Can manage partners'), ('can_manage_projects', 'Can manage projects'), ('can_manage_county_data', 'Can manage county data')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
