# Generated by Django 6.1 on 2026-08-31 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when role was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='parent_role',
            field=models.ForeignKey(blank=True, help_text='Parent role for permission inheritance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='users.role'),
        ),
        migrations.CreateModel(
            name='RoleChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', 'Created'), ('modified', 'Modified'), ('deleted', 'Deleted'), ('permission_added', 'Permission Added'), ('permission_removed', 'Permission Removed'), ('restored', 'Restored')], help_text='Type of change made', max_length=20)),
                ('field_name', models.CharField(blank=True, help_text='Field that was changed (if applicable)', max_length=100)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value', null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the change was made')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text='Role that was changed', on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Change Log',
                'verbose_name_plural': 'Role Change Logs',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['role', '-changed_at'], name='users_rolec_role_id_1ff762_idx'), models.Index(fields=['changed_by', '-changed_at'], name='users_rolec_changed_3d2aa4_idx'), models.Index(fields=['change_type'], name='users_rolec_change__5ebfb0_idx')],
            },
        ),
    ]
