# Generated by Django 5.1.4 on 2026-06-22 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='County code (001-047)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('headquarters', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('coast', 'Coast'), ('eastern', 'Eastern'), ('north_eastern', 'North Eastern'), ('central', 'Central'), ('rift_valley', 'Rift Valley'), ('western', 'Western'), ('nairobi', 'Nairobi')], max_length=20)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('area_sq_km', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Q1 2025', max_length=20)),
                ('fiscal_year', models.CharField(help_text='e.g., 2024/2025', max_length=9)),
                ('quarter_number', models.IntegerField(choices=[(1, 'Q1 (Jan-Mar)'), (2, 'Q2 (Apr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dec)')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Visible for data entry')),
                ('is_closed', models.BooleanField(default=False, help_text='No more submissions allowed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('quarter_number', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('headquarters', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Sub-Counties',
                'ordering': ['county', 'name'],
                'unique_together': {('county', 'name')},
            },
        ),
    ]
