# Generated by Django 6.1 on 2026-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='quarter_number',
            field=models.IntegerField(choices=[(1, 'Q1 (July -Sep)'), (2, 'Q2 (Oct-Dec)'), (3, 'Q3 (Jan-Mar)'), (4, 'Q4 (Apr-Jun)')]),
        ),
    ]
