# Generated by Django 5.1.4 on 2026-06-22 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, help_text='The actual data value (blank if data not available)', max_length=255, null=True)),
                ('target_at_submission', models.DecimalField(blank=True, decimal_places=4, help_text='Target value when this was submitted', max_digits=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked when approved')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this data entry')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='core.county')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='indicators.indicator')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='core.quarter')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['county', 'quarter', 'indicator'],
                'indexes': [models.Index(fields=['county', 'quarter', 'status'], name='data_entry__county__4b44a0_idx'), models.Index(fields=['indicator', 'status'], name='data_entry__indicat_66a11a_idx')],
                'unique_together': {('county', 'quarter', 'indicator')},
            },
        ),
    ]
