# Generated by Django 5.1.4 on 2026-06-22 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('indicator_type', models.CharField(choices=[('impact', 'Impact'), ('outcome', 'Outcome'), ('output', 'Output'), ('action', 'Action/Programme')], default='output', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('percentage', 'Percentage'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('count', 'Count')], max_length=20)),
                ('unit', models.CharField(help_text='e.g., %, per 100,000, births per woman', max_length=100)),
                ('formula', models.TextField(blank=True, help_text='Calculation formula if applicable')),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('source_system', models.CharField(blank=True, help_text='e.g., KNBS, MOH, UNDP', max_length=100)),
                ('frequency', models.CharField(choices=[('annual', 'Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('5_years', '5 Years'), ('10_years', '10 Years')], max_length=20)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Minimum allowed value (leave blank for no minimum)', max_digits=20, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Maximum allowed value (leave blank for no maximum)', max_digits=20, null=True)),
                ('disaggregation_by_age', models.BooleanField(default=False)),
                ('disaggregation_by_sex', models.BooleanField(default=False)),
                ('disaggregation_by_region', models.BooleanField(default=False)),
                ('disaggregation_note', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_custom', models.BooleanField(default=False, help_text='Custom indicator added by project manager')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='indicators.thematicarea')),
            ],
            options={
                'ordering': ['thematic_area', 'code'],
                'indexes': [models.Index(fields=['code'], name='indicators__code_fad439_idx'), models.Index(fields=['thematic_area'], name='indicators__themati_1d067e_idx'), models.Index(fields=['is_active'], name='indicators__is_acti_42b024_idx')],
            },
        ),
    ]
