# Generated by Django 6.1 on 2026-09-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'number'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='sdgs',
            field=models.ManyToManyField(blank=True, help_text='Sustainable Development Goals this indicator contributes to', related_name='indicators', to='indicators.sustainabledevelopmentgoal'),
        ),
    ]
