# Generated by Django 6.1 on 2026-09-01 07:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_sustainabledevelopmentgoal_indicator_sdgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabledevelopmentgoal',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(17)]),
        ),
    ]
