# Generated by Django 5.2 on 2026-09-02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=100, unique=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='report_access_policies', to='users.role')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='report_access_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report access policy',
                'verbose_name_plural': 'Report access policies',
                'ordering': ['report_key'],
            },
        ),
    ]