# Generated by Django 6.1 on 2026-08-31 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldVisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(help_text='Auto-generated report code (e.g., FMR-2025-001)', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', help_text='Report approval status', max_length=20)),
                ('organization_name', models.CharField(help_text='Name of the organization/CBO being monitored', max_length=255)),
                ('location_details', models.TextField(help_text='Specific location/facility details')),
                ('visit_date', models.DateField(help_text='Date of the field visit')),
                ('last_visit_date', models.DateField(blank=True, help_text='Date of the previous visit', null=True)),
                ('report_date', models.DateField(help_text='Date report was compiled')),
                ('data_collection_methods', models.TextField(blank=True, help_text='Methods used to collect data (e.g., interviews, observations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When report was approved', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Person who approved the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visits', to=settings.AUTH_USER_MODEL)),
                ('county', models.ForeignKey(help_text='County where visit took place', on_delete=django.db.models.deletion.PROTECT, related_name='field_visits', to='core.county')),
                ('report_compiled_by', models.ForeignKey(help_text='Person who compiled the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compiled_reports', to=settings.AUTH_USER_MODEL)),
                ('report_submitted_by', models.ForeignKey(help_text='Person who submitted the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Visit Report',
                'verbose_name_plural': 'Field Visit Reports',
                'ordering': ['-visit_date'],
                'permissions': [('can_approve_field_visit', 'Can approve field visits'), ('can_export_field_visit', 'Can export field visit reports')],
            },
        ),
        migrations.CreateModel(
            name='FieldVisitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo', 'Photograph/Evidence'), ('document', 'Document/Report'), ('video', 'Video Recording'), ('data', 'Data/Spreadsheet')], help_text='Type of attachment', max_length=20)),
                ('file', models.FileField(help_text='Attached file', upload_to='field_visits/%Y/%m/')),
                ('description', models.TextField(help_text='Description of attachment')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Field Visit Attachment',
                'verbose_name_plural': 'Field Visit Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(help_text='Name of collaborating organization/partner', max_length=255)),
                ('partnership_nature', models.TextField(blank=True, help_text='Nature of partnership/collaboration')),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=255)),
                ('contact_details', models.CharField(blank=True, help_text='Phone/email for contact', max_length=255)),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='collaborating_partners', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Collaborating Partner',
                'verbose_name_plural': 'Collaborating Partners',
                'ordering': ['partner_name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_description', models.TextField(help_text='Description of challenge/issue identified')),
                ('recommendation', models.TextField(help_text='Recommended solution or action to address challenge')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level for addressing challenge', max_length=20)),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['-priority', 'challenge_description'],
            },
        ),
        migrations.CreateModel(
            name='BestPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_description', models.TextField(help_text='Description of best practice/success story')),
                ('lessons_learned', models.TextField(blank=True, help_text='Key lessons from this practice')),
                ('replicable', models.BooleanField(default=True, help_text='Can this practice be replicated in other areas?')),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='best_practices', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Best Practice',
                'verbose_name_plural': 'Best Practices',
                'ordering': ['practice_description'],
            },
        ),
        migrations.CreateModel(
            name='PersonMet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of person met', max_length=255)),
                ('title', models.CharField(help_text='Title/Position in organization', max_length=255)),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='persons_met', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Person Met',
                'verbose_name_plural': 'Persons Met',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Name of service/activity', max_length=255)),
                ('findings', models.TextField(help_text='Findings observed during visit')),
                ('recommended_action', models.TextField(help_text='Recommended actions based on findings')),
                ('indicator', models.ForeignKey(blank=True, help_text='Associated indicator (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visit_services', to='indicators.indicator')),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='services_provided', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Service Provided',
                'verbose_name_plural': 'Services Provided',
                'ordering': ['service_name'],
            },
        ),
        migrations.CreateModel(
            name='VisitingTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of team member', max_length=255)),
                ('title_organization', models.CharField(help_text='Title/Position and Organization', max_length=255)),
                ('telephone', models.CharField(blank=True, help_text='Contact telephone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('visit', models.ForeignKey(help_text='Associated field visit report', on_delete=django.db.models.deletion.CASCADE, related_name='visiting_team_members', to='field_monitoring.fieldvisitreport')),
            ],
            options={
                'verbose_name': 'Visiting Team Member',
                'verbose_name_plural': 'Visiting Team Members',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='fieldvisitreport',
            index=models.Index(fields=['county', '-visit_date'], name='field_monit_county__dfcfc8_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisitreport',
            index=models.Index(fields=['status'], name='field_monit_status_3c2cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvisitreport',
            index=models.Index(fields=['organization_name'], name='field_monit_organiz_bf4447_idx'),
        ),
    ]
