# Generated by Django 6.1 on 2026-09-01 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_monitoring', '0002_alter_fieldvisitreport_report_submitted_by'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratingpartner',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Select a registered partner when available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_visit_collaborations', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='collaboratingpartner',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Name of collaborating organization/partner', max_length=255),
        ),
    ]
