# Generated by Django 5.1.4 on 2026-06-22 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_submissions', models.BooleanField(default=True, help_text='Receive email for submissions')),
                ('email_approvals', models.BooleanField(default=True, help_text='Receive email for approvals/rejections')),
                ('email_deadlines', models.BooleanField(default=True, help_text='Receive email for deadlines')),
                ('email_reminders', models.BooleanField(default=True, help_text='Receive email reminders')),
                ('in_app_submissions', models.BooleanField(default=True)),
                ('in_app_approvals', models.BooleanField(default=True)),
                ('in_app_deadlines', models.BooleanField(default=True)),
                ('in_app_reminders', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('approval', 'Approval'), ('rejection', 'Rejection'), ('submission', 'Submission'), ('deadline', 'Deadline')], default='info', max_length=20)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=200)),
                ('action_text', models.CharField(blank=True, help_text='Button text for action', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, help_text='Model name e.g., DataEntry', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='Object ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
            },
        ),
    ]
